// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: frequency.proto

package frequencypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FrequencyService_StreamFrequencies_FullMethodName = "/frequency.FrequencyService/StreamFrequencies"
)

// FrequencyServiceClient is the client API for FrequencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FrequencyServiceClient interface {
	StreamFrequencies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FrequencyEntry], error)
}

type frequencyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFrequencyServiceClient(cc grpc.ClientConnInterface) FrequencyServiceClient {
	return &frequencyServiceClient{cc}
}

func (c *frequencyServiceClient) StreamFrequencies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FrequencyEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FrequencyService_ServiceDesc.Streams[0], FrequencyService_StreamFrequencies_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, FrequencyEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FrequencyService_StreamFrequenciesClient = grpc.ServerStreamingClient[FrequencyEntry]

// FrequencyServiceServer is the server API for FrequencyService service.
// All implementations must embed UnimplementedFrequencyServiceServer
// for forward compatibility.
type FrequencyServiceServer interface {
	StreamFrequencies(*emptypb.Empty, grpc.ServerStreamingServer[FrequencyEntry]) error
	mustEmbedUnimplementedFrequencyServiceServer()
}

// UnimplementedFrequencyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFrequencyServiceServer struct{}

func (UnimplementedFrequencyServiceServer) StreamFrequencies(*emptypb.Empty, grpc.ServerStreamingServer[FrequencyEntry]) error {
	return status.Errorf(codes.Unimplemented, "method StreamFrequencies not implemented")
}
func (UnimplementedFrequencyServiceServer) mustEmbedUnimplementedFrequencyServiceServer() {}
func (UnimplementedFrequencyServiceServer) testEmbeddedByValue()                          {}

// UnsafeFrequencyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FrequencyServiceServer will
// result in compilation errors.
type UnsafeFrequencyServiceServer interface {
	mustEmbedUnimplementedFrequencyServiceServer()
}

func RegisterFrequencyServiceServer(s grpc.ServiceRegistrar, srv FrequencyServiceServer) {
	// If the following call pancis, it indicates UnimplementedFrequencyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FrequencyService_ServiceDesc, srv)
}

func _FrequencyService_StreamFrequencies_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FrequencyServiceServer).StreamFrequencies(m, &grpc.GenericServerStream[emptypb.Empty, FrequencyEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FrequencyService_StreamFrequenciesServer = grpc.ServerStreamingServer[FrequencyEntry]

// FrequencyService_ServiceDesc is the grpc.ServiceDesc for FrequencyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FrequencyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "frequency.FrequencyService",
	HandlerType: (*FrequencyServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFrequencies",
			Handler:       _FrequencyService_StreamFrequencies_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "frequency.proto",
}
